version: '3.8'

services:
  warehouse-manager-api:
    image: ghcr.io/tituxmetal/warehouse-manager-api:prod
    container_name: warehouse-manager-api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      SESSION_TTL: ${SESSION_TTL}
      RUN_MIGRATIONS: 'true'
    volumes:
      - data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - reverse-proxy-nw
      - default-nw
    restart: unless-stopped

  warehouse-manager-web:
    image: ghcr.io/tituxmetal/warehouse-manager-web:prod
    container_name: warehouse-manager-web
    environment:
      API_URL: ${API_URL}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
    networks:
      - reverse-proxy-nw
      - default-nw
    restart: unless-stopped
    depends_on:
      - warehouse-manager-api

volumes:
  data:

networks:
  default-nw:
    external: true
  reverse-proxy-nw:
    external: true
